version: 1
type: maven
resolver:
  serverId: tals_artifactory_integration
  snapshotRepo: http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory/zteam-mvn-dev-local
  releaseRepo: http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory/zteam-mvn-dev-local
deployer:
  serverId: tals_artifactory_integration
  snapshotRepo: http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory/zteam-mvn-dev-local
  releaseRepo: http://artifactory-eu.soleng-emea-staging.jfrog.team/artifactory/zteam-mvn-dev-local