pipelines:
  - name: calculate_application
    steps:
      - name: build_app
        type: MvnBuild
        configuration:
          affinityGroup: buildGroup
          sourceLocation: .
          mvnCommand: clean install -f maths/pom.xml -Dmaven.test.skip=true
          configFileLocation: .
          configFileName: config.file.yml
          inputResources:
            - name: calculate_repository_resource
          integrations:
            - name: tals_github_integration
            - name: tals_artifactory_integration
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "8"
        execution:
          onStart:
            - cd $res_calculate_repository_resource_resourcePath/maths

      - name: test_app
        type: MvnBuild
        configuration:
          affinityGroup: buildGroup
          sourceLocation: .
          mvnCommand: clean test -f maths/pom.xml
          configFileLocation: .
          configFileName: config.file.yml
          inputResources:
            - name: calculate_repository_resource
          integrations:
            - name: tals_github_integration
            - name: tals_artifactory_integration
          inputSteps:
            - name: build_app
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "8"
        execution:
          onStart:
            - cd $res_calculate_repository_resource_resourcePath/maths

      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: true
          inputSteps:
            - name: test_app
          outputResources:
            - name: appl_build_info               