name: calculate-ci-job
on:
  push:
    branches: [ master ]
  pull_request:   
    branches: [ master ]
  schedule:
    - cron:  '0 1 * * *'
     
jobs: 
  build-jdk8:
    runs-on: ubuntu-latest
    name: calculate-ci-job
    steps:
    - name: Checkout
      uses: actions/checkout@v1
         
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
        
    - name: Ping JFrog CLI
      run: jfrog rt ping

    - name: Build & Deploy
      run: |
        cd maths && jfrog rt mvn clean install

    - name: Publish Build Information
      run: |
        # Collect environment variables for the build
        jfrog rt bce
        # Collect VCS details from git and add them to the build
        jfrog rt bag
        # Publish build info
        jfrog rt bp       
        
    - name: Xray Scan
      run: |
        jfrog rt bs
        
    - name: Build Promotion
      run: |
        jfrog rt calculate-ci-job ${{github.GITHUB_SHA}} bpr libs-release-staging
