name: CI
on:
  push:
    branches: [ master ]
  pull_request:  
    branches: [ master ]
    
jobs: 
  build-jdk8:
    runs-on: ubuntu-latest
    name: Calculate - Build & Deploy
    steps:
    - uses: actions/checkout@v1
         
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
    - run:
        jfrog rt ping

    - name: Build & Deploy
      run: mvn clean deploy -f maths/pom.xml
      
    - name: Publish Build Information
      run: |
        # Collect environment variables for the build
        jfrog rt bce
        # Collect VCS details from git and add them to the build
        jfrog rt bag
        # Publish build info
        jfrog rt bp
